apiVersion: v1
baseDomain: ecintelligence.lab
metadata:
  name: ocp4
networking:
  machineNetwork:
  - cidr: 10.0.0.0/24
  networkType: OVNKubernetes
compute:
- name: worker
  replicas: 2
controlPlane:
  name: master
  replicas: 3
  platform:
    baremetal: {}
platform:
  baremetal:
    apiVIPs:
      - 10.0.0.10
    ingressVIPs:
      - 10.0.0.12
    provisioningNetworkCIDR: 172.22.0.0/24
    bootstrapExternalStaticIP: 10.0.0.99
    bootstrapExternalStaticGateway: 10.0.0.2
    bootstrapExternalStaticDNS: 10.0.0.2
    hosts:
      - name: cp01
        role: master
        bmc:
          address: ipmi://10.10.0.1:60077
          username: secret
          password: secret
        bootMACAddress: 52:54:00:3a:53:f1
        rootDeviceHints:
         deviceName: "/dev/vda"
      - name: cp02
        role: master
        bmc:
          address: ipmi://10.10.0.1:60080
          username: secret
          password: secret
        bootMACAddress: 52:54:00:05:50:30
        rootDeviceHints:
         deviceName: "/dev/vda"
      - name: cp03
        role: master
        bmc:
          address: ipmi://10.10.0.1:60081
          username: secret
          password: secret
        bootMACAddress: 52:54:00:e0:a3:ec
        rootDeviceHints:
         deviceName: "/dev/vda"
      - name: comp01
        role: worker
        bmc:
          address: ipmi://10.10.0.1:60090
          username: secret
          password: secret
        bootMACAddress: 52:54:00:3f:07:dd
        rootDeviceHints:
          deviceName: "/dev/vda"
      - name: comp02
        role: worker
        bmc:
          address: ipmi://10.10.0.1:60084
          username: secret
          password: secret
        bootMACAddress: 52:54:00:9a:48:34
        rootDeviceHints:
          deviceName: "/dev/vda"
pullSecret: '{"auths":{"xxxxxxx"}}}'
sshKey: 'xxxxxxxxxxx'
